### PR TITLE
Add basic support for aggregates and RIRs

### PR DESCRIPTION
**Pull request by a-d-v**
* Adds aggregate resource
* Adds RIR resource
* Adds aggregates data source

### CODE REVIEW

**Review by roberthstrand — COMMENTED** [review]
Looks good to me! @joakimhellum, anything you have to comment here?

**Comment by tagur87** [comment]
@joakimhellum - We are very interested in this code being merged and released with a new tag version. Is it possible that this could be done soon? We don't want to have to fork this locally as we really appreciate the hard work you have done on this provider, but we are up against a deadline for using these new features.

Thanks so much for your consideration!!

**Comment by joakimhellum** [comment]
@a-d-v @tagur87 Thanks alot for your contributions and very sorry for the slow response. This looks great. We will give this priority. We should be able to create merge this and create new release withins next few hours.

**Comment by joakimhellum** [comment]
Acceptance tests were successful:

```
go test -v ./...
?       github.com/innovationnorway/terraform-provider-netbox   [no test files]
=== RUN   TestAccDataSourceIpamAvailablePrefixes_basic
--- PASS: TestAccDataSourceIpamAvailablePrefixes_basic (16.17s)
=== RUN   TestAccDataSourceIpamPrefix_basic
--- PASS: TestAccDataSourceIpamPrefix_basic (8.13s)
=== RUN   TestAccDataSourceIpamPrefixes_basic
--- PASS: TestAccDataSourceIpamPrefixes_basic (5.26s)
=== RUN   TestAccDataSourceIpamPrefixes_Family
--- PASS: TestAccDataSourceIpamPrefixes_Family (6.72s)
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProvider_impl
--- PASS: TestProvider_impl (0.00s)
=== RUN   TestAccIpamAggregate_basic
--- PASS: TestAccIpamAggregate_basic (4.06s)
=== RUN   TestAccIpamAvailablePrefix_basic
--- PASS: TestAccIpamAvailablePrefix_basic (4.97s)
=== RUN   TestAccIpamPrefix_basic
--- PASS: TestAccIpamPrefix_basic (8.22s)
=== RUN   TestAccIpamRir_basic
--- PASS: TestAccIpamRir_basic (6.49s)
=== RUN   TestAccTag_basic
--- PASS: TestAccTag_basic (4.84s)
PASS
ok      github.com/innovationnorway/terraform-provider-netbox/netbox    66.665s
```

Thanks for this @a-d-v

**Comment by joakimhellum** [comment]
@a-d-v @tagur87 Will go ahead and merge this, then create `v0.1.0-alpha.2` release. We are preparing for `v0.1.0` release within next few days.

**Review by joakimhellum — APPROVED** [review]

**Comment by tagur87** [comment]
Thank you so much @joakimhellum ! This is wonderful.

I was wondering, does this automatically publish to the terraform registry? Or is that a manual step...?
 https://registry.terraform.io/providers/innovationnorway/netbox/latest

**Comment by roberthstrand** [comment]
@tagur87, when a release is created here on GH then the registry picks it up automatically.

**Pull request merged**
